apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.4
  - ingress.yaml
  - app-of-apps.yaml

patchesStrategicMerge:
  - patch-argo-server.yaml
  - patch-argo-secret.yaml
  - patch-argo-cm.yaml
