apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/hjungnitsch/k8s-deploy-repo
    - type: helm
      url: https://helm.releases.hashicorp.com
      name: hashicorp
    - type: helm
      url: https://dl.gitea.io/charts/
      name: gitea