apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  admin.password: $2a$10$NqrMX23gSS6m6Bbveg.JSOeQHmm1JokdtjkvAySC5rBn1s.hZWdEm
  admin.passwordMtime: 2021-02-06T16:10:06CET