apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hjungnitsch/k8s-deploy-repo
    targetRevision: HEAD
    path: deployments/prod/argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true