apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://external-secrets.github.io/kubernetes-external-secrets/'
    targetRevision: 6.2.0
    helm:
      valueFiles:
        - values.yaml
      values: |-
        env:
          VAULT_ADDR: http://vault:8200
          DEFAULT_VAULT_MOUNT_POINT: kubernetes
          DEFAULT_VAULT_ROLE: external-secrets
        serviceAccount:
          create: true
          name: external-secrets
    chart: kubernetes-external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true