apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/minio/operator.git
    targetRevision: v3.0.29
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: operator-minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true