apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.9.1
    helm:
      valueFiles:
        - values.yaml
      values: |-
        injector:
          enabled: false
        server:
          ingress:
            enabled: true
            hosts:
              - host: vault.localtest.me
                paths: ['/']
          dev:
            enabled: true
          postStart:
          - /bin/sh
          - -c
          - |
            vault secrets enable -version=2 kv
            vault auth enable kubernetes
            vault write auth/kubernetes/config \
              token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              kubernetes_host=https://kubernetes.default \
              kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            echo '
            path "kv/*" {
              capabilities = ["list","read"]
            }
            ' | vault policy write read-secrets -
            vault write auth/kubernetes/role/k8s-auth-role \
              bound_service_account_names=vault-auth \
              bound_service_account_namespaces=default \
              policies=read-secrets \
              ttl=1h
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true