apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.9.1
    helm:
      valueFiles:
        - values.yaml
      values: |-
        injector:
          enabled: false
        server:
          ingress:
            enabled: true
            hosts:
              - host: vault.localtest.me
                paths: ['/']
          dev:
            enabled: true
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true