apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullPolicy: IfNotPresent
  credsSecret:
    name: minio-creds-secret

  zones:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi


  mountPath: /export

  requestAutoCert: false


  podManagementPolicy: Parallel

  console:
    image: minio/console:v0.3.26
    replicas: 1
    consoleSecret:
      name: console-secret